## Numpy 

######numeric python or numerical python

In [1]:
## its an library,provides high performance, multi dimensional array object,and also tools 
##create homogeneous data
##dimentions are called axes
##number of axes are called ranks

In [2]:
##Array is a data stucture stores value of same time

In [5]:
#import libaray
import numpy as np

In [ ]:
##ways to create array: np.array,np.zero,no.ones,ets


In [6]:
#creating numpy Array     #np.array we can have array of elements that belongs to other data type.
a=np.array([1,2,3])  #a is list of integer
b=np.array((4,5,6))   #b is turple of integer
print(a)
print(b)

[1 2 3]
[4 5 6]


In [10]:
#np.arrange (start,end,steps)
a=np.arange(5,50,2)
print(a)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]


In [16]:
#np.linspace (start,end,num of output)
a=np.linspace(1,2/3,4)
print(a)

[1.         0.88888889 0.77777778 0.66666667]


In [17]:
#create np.array from list
l=[1,2,3,4,5,6,7,8,9]
arr=np.array(l)
print("numpy array created from list",arr)

numpy array created from list [1 2 3 4 5 6 7 8 9]


In [19]:
#create numpy array from tuple
l=(1,2,3,4,5,6,7,8,9)
arr=np.array(l)
print("numpy array from tuple",arr)

numpy array from tuple [1 2 3 4 5 6 7 8 9]


In [20]:
type(arr)

numpy.ndarray

In [24]:
#np.ones
a=np.ones((4,6))
dtype=np.int16
print(a)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [29]:
#np.zeroes
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [2]:
import numpy as np

In [3]:
#np.full
a=np.full((3,4),2)
print(a)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [4]:
np.random.randint(100,200,10)

array([182, 142, 195, 117, 156, 137, 115, 172, 136, 134])

In [31]:
#np.random
a=np.random.rand(3,2)
print(a)

[[0.22130142 0.71916473]
 [0.92056562 0.33418184]
 [0.91295692 0.95247345]]


In [34]:
#np.empty
a=np.empty((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [40]:
import numpy as np
import pandas as pd
s=np.random.randn(10)
print("the orignal series is:")
print(s)

the orignal series is:
[ 1.12314454  0.55353213 -0.9611053   0.9129052  -0.15501255  0.67310733
 -0.54892721  2.31869643 -0.46731815  1.18616876]


In [43]:
s.head(4)

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [44]:
lst=[1,2,3,4]
arr=np.array(lst)

In [50]:
#np.flatten()
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array is:",str(a))


2D array is: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
b=a.flatten()
print("1D Array is:",b)

1D Array is: [1 2 3 4 5 6 7 8 9]


In [54]:
#np.ravel()
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array is:",str(a))
b=a.ravel()
print("1D array is:",b)

2D array is: [[1 2 3]
 [4 5 6]
 [7 8 9]]
1D array is: [1 2 3 4 5 6 7 8 9]


In [65]:
##np.reshape()
a=np.array([[1,2,3],[4,5,6],[7,8,9],[2,3,9]])
print("2D array is:",a)
b=a.reshape(6,2)
print("new array:",b)

2D array is: [[1 2 3]
 [4 5 6]
 [7 8 9]
 [2 3 9]]
new array: [[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 2]
 [3 9]]


In [66]:
lst1=[1,2,3,4]
lst2=[5,6,7,8]
lst3=[9,8,7,6]
arr1=np.array([lst1,lst2,lst3])

In [68]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6]])

In [7]:
type(arr)

numpy.ndarray

In [13]:
lst1=[1,2,3,4]
lst2=[5,6,7,8]
lst3=[9,8,7,6]
arr1=np.array([lst1,lst2,lst3])

In [14]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6]])

In [15]:
arr1.shape  #imp

(3, 4)

In [16]:
type(arr1)

numpy.ndarray

In [17]:
#indexing
arr[3]

4

In [20]:
arr[3]=5

In [21]:
arr

array([1, 2, 3, 5])

In [22]:
arr[1:3]

array([2, 3])

In [23]:
arr[-1]

5

In [24]:
arr[1:]

array([2, 3, 5])

In [25]:
arr[:3]

array([1, 2, 3])

In [27]:
arr[:-1] #removes last no.

array([1, 2, 3])

In [28]:
arr[::-1]

array([5, 3, 2, 1])

In [29]:
arr[::-2] #jumps 2 step

array([5, 2])

In [30]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6]])

In [31]:
arr1[:,1]

array([2, 6, 8])

In [69]:
 arr[1:1]

array([], dtype=int32)

In [73]:
arr1[1:,2:]

array([[7, 8],
       [7, 6]])

In [34]:
arr1[1:,1:3]

array([[6, 7],
       [8, 7]])

In [36]:
arr1[1:,0:2]

array([[5, 6],
       [9, 8]])

In [78]:
arr1[1:,2:]

array([[7, 8],
       [7, 6]])

In [79]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6]])

In [77]:
arr1[::-2]

array([[9, 8, 7, 6],
       [1, 2, 3, 4]])

In [74]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6]])

In [75]:
arr1[1:,0:2]

array([[5, 6],
       [9, 8]])

In [40]:
arr1[1:2,1:3]

array([[6, 7]])

In [41]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6]])

In [42]:
arr1[0:,3:]

array([[4],
       [8],
       [6]])

In [45]:
arr1[:,::-4]

array([[4],
       [8],
       [6]])

In [46]:
#EDA
arr

array([1, 2, 3, 5])

In [47]:
arr>1

array([False,  True,  True,  True])

In [48]:
arr1.shape

(3, 4)

In [49]:
arr1.reshape(6,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 8],
       [7, 6]])

In [59]:
#mechaism to create an array
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [62]:
np.arange(1,20,2).reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [63]:
arr*arr

array([ 1,  4,  9, 25])

In [65]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [72]:
np.random.randint(10,50) #upper and lower value has to be added

36

In [73]:
np.random.randint(10,50,4).reshape(2,2) #upper and lower value along with the size

array([[34, 19],
       [25, 48]])

In [71]:
np.random.randn()

1.1961947352730518

In [74]:
np.random.randn(5,6) #standard divation

array([[ 0.35683317, -0.34375206, -0.01672004,  0.27562318, -0.77682684,
        -0.62043559],
       [-2.0239944 ,  0.33453128, -0.52805046, -0.30986624, -0.29257271,
        -0.76876341],
       [ 1.04485406,  0.34103353, -0.31013293,  0.72003954,  0.45818553,
         0.18869095],
       [-1.45887648, -0.76956561,  0.84262429,  0.62127371, -0.09690001,
         0.61214927],
       [ 0.38332004, -0.75379864, -0.88157703, -0.29724664, -0.7166952 ,
        -0.09316005]])

In [75]:
np.random.random_sample((4,7))

array([[2.01488185e-01, 1.47682412e-01, 3.39368180e-01, 1.59687834e-01,
        4.82753344e-01, 8.49218117e-01, 1.43852540e-02],
       [8.54265257e-01, 6.16795782e-01, 2.73183726e-01, 4.92026279e-01,
        4.38676766e-01, 5.56404459e-01, 8.88413142e-01],
       [4.45232772e-01, 9.10137585e-04, 4.36811453e-01, 4.39266015e-01,
        6.29087163e-01, 5.38423742e-02, 5.50200497e-01],
       [5.07495321e-01, 9.88440017e-01, 3.55573540e-01, 4.22987752e-01,
        3.29744617e-01, 6.16037213e-01, 1.24006687e-02]])

In [7]:
#Array Concatenate np.concatenate()
#concatenating two arrays
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.concatenate([a,b])
print(c)

[1 2 3 4 5 6 7 8]


In [8]:
type(c)

numpy.ndarray

In [9]:
type(a)

numpy.ndarray

In [12]:
#concatenate two 2D array
#takes tuple or list of array
#number of dimentions should be same
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[5,6,7]])
c=np.concatenate([a,b])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [5 6 7]]


In [13]:
#concatenating three 1D array
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
d=np.concatenate([a,b,c])
print(d)

[1 2 3 4 5 6 7 8 9]


In [14]:
#concatenating two 2d array columnwise
a=([[1,2,3],[4,5,6]])
b=([[5,6,9],[3,4,2]])
c=np.concatenate([a,b],axis=1)
print(c)

[[1 2 3 5 6 9]
 [4 5 6 3 4 2]]


In [18]:
#np.vstack() np.hstack
#concatenat different dimension
#Concatenating using vstack
a=np.array([1,2,3])
b=np.array([[3,4,5],[6,7,8]])
c=np.vstack([a,b])
print(c)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [21]:
#concatenate using hstack
a=([[1,2,3],[2,6,7]])
b=([[4,5,6],[7,8,9]])
c=np.hstack([a,b])
print(c)

[[1 2 3 4 5 6]
 [2 6 7 7 8 9]]


In [25]:
#Appending Array
#two array can be appendend in such a way that value from second array are glued to the end of the first array
#appending a 1D array
a=np.array([1,3,4])
b=np.array([4,7,8,9,0])
c=np.append(a,b)
print(c)

[1 3 4 4 7 8 9 0]


In [32]:
#appending 2D array
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,5,6],[6,9,7],[3,4,2]])
c=np.append(a,b,axis=1)
print(c)

[[1 2 3 4 5 6]
 [4 5 6 6 9 7]
 [7 8 9 3 4 2]]


In [40]:
#splitting of array 
#vsplite
a=np.arange(16).reshape(4,4)

upper,lower=np.vsplit(a,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [45]:
#hsplite
a=np.arange(16).reshape(4,4)
left,right=np.hsplit(a,[2])
print("right side\n",right)
print("left side\n",left)

right side
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
left side
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [50]:
#numpy broadcast
#used while performing Arithemetic operations are performed on array of different shape
x=np.ones((4,3))
print("value of x\n",x)
print("dimention of x",x.shape)
print("dimention of y",y.shape)
y=np.random.random((4,3))
print("value of y\n",y)
print(x+y)

value of x
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
dimention of x (4, 3)
dimention of y (4, 3)
value of y
 [[0.44336452 0.35604792 0.67211884]
 [0.64827707 0.85659857 0.57975152]
 [0.34485406 0.89814159 0.93683507]
 [0.04800923 0.36894889 0.74779084]]
[[1.44336452 1.35604792 1.67211884]
 [1.64827707 1.85659857 1.57975152]
 [1.34485406 1.89814159 1.93683507]
 [1.04800923 1.36894889 1.74779084]]


In [55]:
x=np.ones((3,5))
y=np.random.random((3,5))
print(x+y)

[[1.97035448 1.21739466 1.59817767 1.80502172 1.27206571]
 [1.59367717 1.01587061 1.70273078 1.96499675 1.89429559]
 [1.01048692 1.37715428 1.7727734  1.42960157 1.22727963]]


In [60]:
x=np.ones((3,5))
y=np.arange(2,3,4)
print(y)
print(x)
print(x-y)

[2]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]


In [64]:
x=np.ones((3,4))
y=np.arange((2,1,4))
print(x-y)

TypeError: arange: scalar arguments expected instead of a tuple.

### Performing mathematical operation

In [65]:
#performing mathematical operation on numpy array
#np.add(),np.subract(),np.multiple(),np.divide,np.remainder()
#a.sum()-array wise sum
#a.min()-array wise minimum value
#b.max(axis=0)-maximum value of an array row
#b.cumsum(axis=1)-cumulative sum of the elements
#a.mean()---mean
#b.median()---median
#a.corrcoef()---correlation coefficient
#np.std(b)---standard deviation
#exponentiation--np.exp()
#square root----np.sqrt()
#natural logarithm---np.log()
#sin cos---np.sin() np.cos()


In [73]:
import numpy as np
a=np.arange(1,10,1)
print("value of a:\n",a)
print("value less than 5:\n",a[a>5])
print(a[(a>6)|(a%2==0)])

value of a:
 [1 2 3 4 5 6 7 8 9]
value less than 5:
 [6 7 8 9]
[2 4 6 7 8 9]


### Transposing arrays


In [74]:
#it means switching its dimension
#T() and np.transpose()
#no effect on 1D array

In [76]:
a=np.arange(1,6,1)
print("orignal\n",a)
b=np.transpose(a)
print("transpose\n",b)  #no effect on 1D array

orignal
 [1 2 3 4 5]
transpose
 [1 2 3 4 5]


In [82]:
a=np.full((3,4),6)
print("orignal\n",a)
b=a.T
print("transpose\n",b)

orignal
 [[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
transpose
 [[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]]


In [83]:
##Inserting and deleting array elements
#numpy.insert(arr,obj,values,axis)
#arr-input array
#obj--specifies the index before which insertion is to be made
#values--array of a value to be inserted
#axis--denotes the axis along which value have to be inserted


In [85]:
#inserting values in Array
a=np.array([1,2,3,4,5,6])
print("orignal\n",a)
a=np.insert(a,3,20)
print ("inserted\n",a)

orignal
 [1 2 3 4 5 6]
inserted
 [ 1  2  3 20  4  5  6]


In [86]:
#Deleting Array
#np.delete(arr,obj,axis)

In [89]:
a=np.arange(10)
print("orignal:\n",a)
print("shape of a:\n",a.shape)
b=np.delete(a,5)
print("after deleting:\n",b)
print("shape of b:\n",b.shape)
c=np.delete(a,[6,7])
print("shape of c:\n",c.shape)

orignal:
 [0 1 2 3 4 5 6 7 8 9]
shape of a:
 (10,)
after deleting:
 [0 1 2 3 4 6 7 8 9]
shape of b:
 (9,)
shape of c:
 (8,)


In [91]:
#check if numpy array is empty
a=np.arange(12).reshape(3,4)
print(a)
if(a.size==0):
    print("the given array is empty")
else:
    print("the give array is\n",a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
the give array is
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [93]:
#find index of a value
a=np.arange(10)
print(a)
index=np.where(a==6)
print(index)

[0 1 2 3 4 5 6 7 8 9]
(array([6], dtype=int64),)


In [96]:
a=np.arange(10)
print(a)
index=np.where(a==6)
print(index[0]) #index[0]---tells only location and not data type

[0 1 2 3 4 5 6 7 8 9]
[6]


In [103]:
#sorting
a=np.array([4,8,6,2,1,3,0])
print(a)
a.sort()
print("after sort:\n",a)


[4 8 6 2 1 3 0]
after sort:
 [0 1 2 3 4 6 8]


In [104]:
#Normalize array
#normalize an array is the process of bringing the array value to some defined range.
#x=(x-xmin)/(xmax-xmin)

In [105]:
a=np.array([450,453,390,980])
max=a.max()
min=a.min()
a=(a-max)/(max-min)
print("after normalize:",a)


after normalize: [-0.89830508 -0.89322034 -1.          0.        ]


In [7]:
#subset 
import numpy as np
a=np.arange(36).reshape(3,4,3)
print(a)
b=a.compress([1,1,1])
print (b)
c=a.compress([0,0,1,1,1])
print(c)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
[0 1 2]
[2 3 4]


In [10]:
#Remove a redundant dimension 
a=np.array([[1,2,3,4]])
print("2D array\n",a)
b=a.squeeze()
print("after reducing dimension:\n",b)

2D array
 [[1 2 3 4]]
after reducing dimension:
 [1 2 3 4]


In [12]:
#retrive diagonals 
a=np.arange(27).reshape(3,3,3)
print("3D array\n:",a)
print("Diagonal elements for Axis1=1 AND Axis2=2 ARE:\n")
print(a.diagonal(axis1=1,axis2=2))

3D array
: [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Diagonal elements for Axis1=1 AND Axis2=2 ARE:

[[ 0  4  8]
 [ 9 13 17]
 [18 22 26]]


In [13]:
#Subsetting Numpy array using indexing
a=np.arange(56,106,2).reshape(5,5)
print("2D array:\n",a)


2D array:
 [[ 56  58  60  62  64]
 [ 66  68  70  72  74]
 [ 76  78  80  82  84]
 [ 86  88  90  92  94]
 [ 96  98 100 102 104]]


In [14]:
a[:0]

array([], shape=(0, 5), dtype=int32)

In [15]:
a[:,0]

array([56, 66, 76, 86, 96])

In [18]:
a=np.arange(1,10,1).reshape(3,3)
print(a)
print("purely integer indexing:\n",a[[0,1,2],[2,1,0]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
purely integer indexing:
 [3 5 7]


### Phython programs


In [19]:
#insert row as well as column of 2d array
import numpy as np
a=np.arange(12).reshape(4,3)
print(a)
print("shape of a:\n",a.shape)
a=np.insert(a,1,5,axis=1)
print("after insertion;\n",a)
print("shape:",a.shape)
a=np.insert(a,2,6,axis=0)
print("array after insertion:\n",a)
print("shape:",a.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
shape of a:
 (4, 3)
after insertion;
 [[ 0  5  1  2]
 [ 3  5  4  5]
 [ 6  5  7  8]
 [ 9  5 10 11]]
shape: (4, 4)
array after insertion:
 [[ 0  5  1  2]
 [ 3  5  4  5]
 [ 6  6  6  6]
 [ 6  5  7  8]
 [ 9  5 10 11]]
shape: (5, 4)


In [24]:
#insert element in row as well as in a column of a 2D array at mulyiple  insertion point
a=np.arange(12).reshape(4,3)
print(a)
#insert 7 after 1 and 5
a=np.insert(a,(1,5),7)
print("after insert:\n",a)
print(a.shape)
a=np.arange(12).reshape(4,3)
#8 will be inserted before first and second column
a=np.insert(a,(1,2),8,axis=1)
print("after insert",a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
after insert:
 [ 0  7  1  2  3  4  7  5  6  7  8  9 10 11]
(14,)
after insert [[ 0  8  1  8  2]
 [ 3  8  4  8  5]
 [ 6  8  7  8  8]
 [ 9  8 10  8 11]]


In [5]:
##3 INtersection and difference

In [7]:
n1=np.array([10,20,30,40])
n2=np.array([50,40,80,90])


In [8]:
#intersection
np.intersect1d(n1,n2)

array([40])

In [10]:
#unique in n2
np.setdiff1d(n2,n1)

array([50, 80, 90])

In [11]:
#unique in n1
np.setdiff1d(n1,n2)

array([10, 20, 30])