# Pandas 


In [1]:
#Pandas dataframe

In [3]:
import pandas as pd
import numpy as np

In [8]:
A=np.arange(0,20).reshape(5,4)

In [10]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [17]:
##create dataframe
df=pd.DataFrame(A,index=["Row1","Row2","Row3","Row4","Row5"],columns=["column1",
                                                           "column2",
                                                           "column3",
                                                           "column4"])

In [18]:
df

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [19]:
df.head()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [20]:
df.tail()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [22]:
df=pd.DataFrame(np.arange(0,20).reshape(4,5),index=["Row1","Row2","Row3","Row4"],columns=["column1","column2","column3","column4","column5"])

In [23]:
df

column1  column2  column3  column4  column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19

In [25]:
df.head()

column1  column2  column3  column4  column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19

In [26]:
type(df)

pandas.core.frame.DataFrame

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Row1 to Row4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  4 non-null      int32
 1   column2  4 non-null      int32
 2   column3  4 non-null      int32
 3   column4  4 non-null      int32
 4   column5  4 non-null      int32
dtypes: int32(5)
memory usage: 112.0+ bytes


In [29]:
df.describe()

column1    column2    column3    column4    column5
count   4.000000   4.000000   4.000000   4.000000   4.000000
mean    7.500000   8.500000   9.500000  10.500000  11.500000
std     6.454972   6.454972   6.454972   6.454972   6.454972
min     0.000000   1.000000   2.000000   3.000000   4.000000
25%     3.750000   4.750000   5.750000   6.750000   7.750000
50%     7.500000   8.500000   9.500000  10.500000  11.500000
75%    11.250000  12.250000  13.250000  14.250000  15.250000
max    15.000000  16.000000  17.000000  18.000000  19.000000

In [30]:
#indexing
##colum name,rowindex[loc],rowindex columnindex number[.iloc]

In [32]:
df.head()

column1  column2  column3  column4  column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19

In [35]:
df["column1"]

Row1     0
Row2     5
Row3    10
Row4    15
Name: column1, dtype: int32

In [34]:
df[["column1","column2"]] #more than 1 colum multinested list

column1  column2
Row1        0        1
Row2        5        6
Row3       10       11
Row4       15       16

In [37]:
type(df[["column1","column2"]])

pandas.core.frame.DataFrame

In [36]:
type(df["column1"])

pandas.core.series.Series

In [38]:
#difference between pandas and series :pandas\df has multiple combination of rows and columns
#series :single row or column


In [40]:
df.loc["Row3"] #directly with the name of row we get both rows and column

column1    10
column2    11
column3    12
column4    13
column5    14
Name: Row3, dtype: int32

In [41]:
#iloc
df.head()

column1  column2  column3  column4  column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19

In [42]:
#iloc= indexing both rows and columns 
#left side row
#right side column
df.iloc[2:4,0:2]


column1  column2
Row3       10       11
Row4       15       16

In [43]:
df.iloc[2:,1:]

column2  column3  column4  column5
Row3       11       12       13       14
Row4       16       17       18       19

In [44]:
#convert dataframe into array
df.iloc[:,1:].values

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [47]:
arr3=df.iloc[2:4,0:3].values

In [48]:
arr3

array([[10, 11, 12],
       [15, 16, 17]])

In [51]:
#Basic operation
df.isnull().sum()

column1    0
column2    0
column3    0
column4    0
column5    0
dtype: int64

In [52]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,2,3]],index=["Row1","Row2"],columns=["column1","column2","column3"])

In [53]:
df

column1  column2  column3
Row1        1      NaN        2
Row2        1      2.0        3

In [54]:
df.isnull().sum()

column1    0
column2    1
column3    0
dtype: int64

In [55]:
df.isnull()

column1  column2  column3
Row1    False     True    False
Row2    False    False    False

In [56]:
df.isnull().sum()==0

column1     True
column2    False
column3     True
dtype: bool

In [59]:
df["column3"].value_counts()

2    1
3    1
Name: column3, dtype: int64

In [60]:
df["column2"].unique()

array([nan,  2.])

In [62]:
 df[df["column2"]>2]

Empty DataFrame
Columns: [column1, column2, column3]
Index: []

# Pandas 


In [63]:
#stringIO
#pandas read_csv

In [70]:
data=("column1,column2,column3\n"
     "x,y,1\n"
      "a,b,2\n"
     "c,d,3")

In [71]:
type(data)

str

In [72]:
 from io import StringIO

In [73]:
#in memory file format
StringIO(data)

In [83]:
pd.read_csv(StringIO(data))

column1 column2  column3
0       x       y        1
1       a       b        2
2       c       d        3

In [87]:
 pd.read_csv(StringIO(data),usecols=['column1','column2'])

column1 column2
0       x       y
1       a       b
2       c       d

In [90]:
df.to_csv("test.csv",index=False) #save file to csv formate index=false no index

In [93]:
#datatypes in csv
data=("column1,column2,column3,column4\n"
     "x,y,z,1\n"
      "a,b,c,2\n"
     "c,d,3")

In [98]:
df=pd.read_csv(StringIO(data),dtype="object")#dtype changes data to object

In [96]:
df

column1 column2 column3  column4
0       x       y       z      1.0
1       a       b       c      2.0
2       c       d       3      NaN

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   column1  3 non-null      object
 1   column2  3 non-null      object
 2   column3  3 non-null      object
 3   column4  2 non-null      object
dtypes: object(4)
memory usage: 224.0+ bytes


In [100]:
df.head()

column1 column2 column3 column4
0       x       y       z       1
1       a       b       c       2
2       c       d       3     NaN

In [101]:
df.isnull().sum()

column1    0
column2    0
column3    0
column4    1
dtype: int64

In [102]:
df["column1"]

0    x
1    a
2    c
Name: column1, dtype: object

In [15]:
import pandas as pd
import numpy as np
from io import StringIO

In [16]:
data=("column1,column2,column3,column4\n"
     "x,y,z,1\n"
      "a,b,c,2\n"
     "c,d,3")

In [17]:
df=pd.read_csv(StringIO(data),dtype="object")

In [18]:
df

column1 column2 column3 column4
0       x       y       z       1
1       a       b       c       2
2       c       d       3     NaN

In [20]:
df.dtypes

column1    object
column2    object
column3    object
column4    object
dtype: object

In [21]:
data=('index,a,b,c\n'
     '4,apple,bat,5.7\n'
     '8,orange,cow,10')

In [22]:
pd.read_csv(StringIO(data))

index       a    b     c
0      4   apple  bat   5.7
1      8  orange  cow  10.0

In [23]:
pd.read_csv(StringIO(data),index_col=0)

a    b     c
index                   
4       apple  bat   5.7
8      orange  cow  10.0

In [24]:
#use index cols and usecols
data=('a,b,c\n'
     '4,apple,bat,\n'
     '8,orange,cow')

In [25]:
pd.read_csv(StringIO(data),usecols=['b','c'],index_col=0)

b   c
4  bat NaN
8  cow NaN